### ISSUE TITLE
Visual Editor: Not showing images on site

### ISSUE THREAD

**Issue by SiteglideAPI** [Siteglide/Siteglide-Admin-Feedback#1]
## Current behaviour:
When clicking an image in a content section in VE it does not show the list of existing images.

## Expected behaviour: 
It shows the list of images.

## Steps to Reproduce

1. Edit a content section and click on an image

## Environment
https://townhall-demo.staging-oregon.near-me.com
Safari on Mac from v2.0.0 of CMS

## Media
http://files.siteglide.com/1C413l2B3X1X

**Comment by DeanmvSG** [comment]
Fixed in v2.0.2
