### ISSUE TITLE
Code Editor - cannot create filepaths anymore

### ISSUE THREAD

**Issue by MartinWysi** [Siteglide/Siteglide-Admin-Feedback#13]
## Expected Behavior
When viewing Code Editor within the Admin you should be able to right click "create file" on an existing folder and then enter the desired path. This should then create the folder structure down to your new file. 

## Current Behavior
At the moment, you right click "create file" on an existing folder and then enter the desired path and nothing happens.

## Steps to Reproduce
http://file.siteglide.com/55da6e8e65f1

## Environment
* macOS 10.13.6
* Chrome 68.0.3440.106
* Siteglide Admin v2.1.3

**Comment by mattwalter91** [comment]
@MartinWysi - For the assets folder, only CSS and JS are supported currently. I'll make a note to open this up, but it isn't a bug per se.
