### ISSUE TITLE
Code Editor - 'add tags' missing from layouts

### ISSUE THREAD

**Issue by MartinWysi** [Siteglide/Siteglide-Admin-Feedback#14]
## Expected Behavior
When editing a WebApp layout within the Code Editor, there should be a dropdown to allow for quick access to adding liquid tags into the file. 

## Current Behavior
This dropdown is not currently visible.

## Steps to Reproduce
1. Open Code Editor within the Admin
2. navigate to a WebApp layout file within Code Editor
3. Look along the top of the code editor

## Environment
* macOS 10.13.6
* Chrome 68.0.3440.106
* Siteglide Admin v2.1.3

## Media
http://file.siteglide.com/314e4a5a521a

**Comment by mattwalter91** [comment]
@MartinWysi - Could you take another look at this one please, as it's now working for me...

**Comment by MartinWysi** [comment]
@mattwalter91  yes, it's now visible for me too - though is not sitting correctly:
http://file.siteglide.com/91357de1980e
chrome - 69.0.3497.81

**Comment by mattwalter91** [comment]
@MartinWysi - Fixed for next release
