### ISSUE TITLE
Menus - Create new Menu issue

### ISSUE THREAD

**Issue by MartinWysi** [Siteglide/Siteglide-Admin-Feedback#15]
If a site has no menus at all when you create one it duplicates and breaks the menu.

## Expected Behavior
When creating a new menu, you should hit save and a single menu should be created without duplicating the items within your menu either.

## Current Behavior
Currently, you hit save and the system creates two menus, the first of which is empty, the second has duplications of the items you added to the menu.

## Steps to Reproduce
http://file.siteglide.com/113w302y0Y3D
https://siteglide-admin.oregon.near-me.com/#/cms/menu-builder

## Context (Environment)
Siteglide v2.0.2.

**Comment by mattwalter91** [comment]
@MartinWysi - You hit save twice. I'll set it up to disable the save button when processing live we have elsewhere.

**Comment by mattwalter91** [comment]
Fixed. Will be in next release.
