### ISSUE TITLE
Menus - pageSlug under pagename is incorrect

### ISSUE THREAD

**Issue by MartinWysi** [Siteglide/Siteglide-Admin-Feedback#16]
The pageSlug beneath Menu items when editing/creating a Menu is incorrect. It is correct everywhere else.

## Expected Behavior
The pageSlug should be "/about" or "/contact" or "/" (home).

## Current Behavior
Currently the slug displays  "/about/" or "/contact/" or "//" (home). It is correct in all other locations, such as the edit modal for the Menu item and when clicked on the frontend site.

## Steps to Reproduce
http://file.siteglide.com/0M2n2W2O1m0P
https://siteglide-admin.oregon.near-me.com/#/cms/menu-builder/11149

## Context (Environment)
Siteglide v2.0.2.

**Comment by mattwalter91** [comment]
Fixed in v2.1.2
