### ISSUE TITLE
Sidebar item 'selected' class changes even if page doesn't

### ISSUE THREAD

**Issue by tom-websu** [Siteglide/Siteglide-Admin-Feedback#2]
## Expected Behaviour
The selected item should only show on pages when page change has been successful.

## Current Behaviour
Selected item can change if page change is started but doesn't complete successfully.

## Steps to Reproduce
1. Open a menu in the "Menu Builder" and make a change without saving.
2. In the left hand menu select the "Company Information" item to try and change the page.
3. When prompted about unsaved changes by the javascript confirm() select "Cancel".
4. You should see the "selected" class is applied to "Company Information" even if the page doesn't change.

## Environment
Example: 
* macOS 10.13.5
* Google Chrome 67.0.3396.99
* Siteglide Admin v2.0.0

## Media
![menu-selected](https://user-images.githubusercontent.com/17270217/43466426-686ca48a-94d7-11e8-9aa1-ffc1784435d4.png)

**Comment by DeanmvSG** [comment]
Thanks @tom-websu 

We will update shortly and close this issue when we're happy it's fixed! 👍

**Comment by mattwalter91** [comment]
@tom-websu - Fixed in v2.0.1
