### ISSUE TITLE
Content Sections - No Delete Button

### ISSUE THREAD

**Issue by MartinWysi** [Siteglide/Siteglide-Admin-Feedback#22]
## Expected Behavior
There should be a delete button on both list and detail view for content sections in the Admin UI.

## Current Behavior
There is no button to allow for deletion.

## Steps to Reproduce
1. Navigate to CMS > Content Sections.
2. Note the absence of a delete button.

## Context (Environment)
Siteglide Admin v2.1.2

**Comment by mattwalter91** [comment]
@MartinWysi - There is no DELETE endpoint yet. This is for the Roadmap, not Issues.
