### ISSUE TITLE
Bug - Hiding Page Settings

### ISSUE THREAD

**Issue by SplicedWeb** [Siteglide/Siteglide-Admin-Feedback#23]
## Expected Behavior
Clicking "HIDE PAGE SETTINGS" when in pages/pagname should hide PAGE NAME/URL/TEMPLATE/OG/SEO fields

## Current Behavior
Open Graph Settings remain visible behind/under the code editor

## Steps to Reproduce
- To recreate, first expand SEO and OPEN GRAPH sections, then click "HIDE PAGE SETTINGS"

## Environment
Windows 10 / Chrome Version 68.0.3440.106
Siteglide Admin - v2.1.3

## Media

![2018-09-13_2052og](https://user-images.githubusercontent.com/8891318/45484352-2d22cc00-b797-11e8-82ea-e34c2d4275cd.png)

**Comment by mattwalter91** [comment]
@SplicedWeb - Thanks Nathan. This has been fixed and will be in our next release.
