### ISSUE TITLE
Dropdown fields stick on scroll

### ISSUE THREAD

**Issue by MartinWysi** [Siteglide/Siteglide-Admin-Feedback#25]
## Expected Behavior
If you open a dropdown and then scroll, the output should stick to the field, or, alternatively become hidden again.

## Current Behavior
If you open a dropdown and then scroll, the output sticks to the same position and becomes detached from the field.

## Steps to Reproduce
http://file.siteglide.com/b46098bcf32c

## Environment
Mac 10.13.6
Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Siteglide v2.2.0

**Comment by mattwalter91** [comment]
Fixed in next release
