### ISSUE TITLE
Tooltips show the default value

### ISSUE THREAD

**Issue by MartinWysi** [Siteglide/Siteglide-Admin-Feedback#26]
When setting up or editing and item within the "Includes" section (banner, footer, header etc).  The tooltip on item name has the default "This is a tooltip" value

<img width="1552" alt="screen shot 2018-08-02 at 09 53 47" src="https://user-images.githubusercontent.com/15265711/43573815-8c130064-963a-11e8-961b-f54ffeb46d29.png">
<img width="420" alt="screen shot 2018-08-02 at 09 54 40" src="https://user-images.githubusercontent.com/15265711/43573816-8c310bcc-963a-11e8-9132-f3161e0cf260.png">

**Comment by MartinWysi** [comment]
@mattwalter91  Page names says "Only Visible to users within your Siteglide Admin" so make it the same as that. Also, if we're not allowed to use special characters at the moment can you add that to both?

**Comment by mattwalter91** [comment]
@MartinWysi - Sorry, which field are we talk about in regards to special characters?

**Comment by MartinWysi** [comment]
@mattwalter91  its okay we're dealing with special characters in another issue so ignore that part for now. I'm going to mark this as more input required from my end for now - so a revamp of all Tooltips is on my to-do list and would be easier to do all at once.
