### ISSUE TITLE
Menu Builder - Not working correctly (or at all)

### ISSUE THREAD

**Issue by Mario-Kostadinov** [Siteglide/Siteglide-Admin-Feedback#29]
## Steps to Reproduce

1. Menu Builder
2. Create a new menu
3. Add Links to the menu
4. Re-open the new menu and nothing shows up

## Environment

Example: 
* macOS 10.13.6
* Google Chrome 68.0.3440.75
* Siteglide Admin v2.2.2

## Media

![screenshot 2018-10-18 at 14 59 34](https://user-images.githubusercontent.com/16762580/47152816-74483380-d2e6-11e8-8102-864ed9c2ce35.png)

**Comment by SiteglideAPI** [comment]
Thanks @Mario-Kostadinov  this is a known issue and will be fixed in the next release.
