### ISSUE TITLE
Liquid Errors - Toolbox Content

### ISSUE THREAD

**Issue by Eireternal** [Siteglide/Siteglide-Admin-Feedback#3]
## Expected Behavior

I would expect the liquid includes to render text, imagery etc.
## Current Behavior

Instead the output shows the liquid error and exposes the code in the browser.
## Steps to Reproduce

1. Under CMS, navigate to the "About" page. 
2. Scroll down to the editor under "Page Item"
3. Select an include from the Toolbox and insert the code in editor
4. Click save and preview the page in a browser.
5. Notice the liquid tag errors.

## Environment

* Windows 10 Pro 10.0.16299 
* Google Chrome 67.0.3396.99
* Siteglide Admin v2.0.0

## Media

![image](https://user-images.githubusercontent.com/7497639/43481484-ebbb6ca8-94ba-11e8-8f02-d6bc1244591e.png)
![image](https://user-images.githubusercontent.com/7497639/43481500-f45a18dc-94ba-11e8-8eca-9f7e6e3b8b65.png)

**Comment by Eireternal** [comment]
You are correct Dean, however this will still occur if you add only 1 item from the toolbox. So for example, if I remove the other liquid tags and just keep that first one for 'section_button', I still get that error.

![image](https://user-images.githubusercontent.com/7497639/43482313-30c2b106-94bd-11e8-89e8-f17dabd11c13.png)

![image](https://user-images.githubusercontent.com/7497639/43482324-3b0a7f0e-94bd-11e8-83ec-fcbdc557e1bd.png)

**Comment by DeanmvSG** [comment]
Thanks for the better example! We’ll check these over tomorrow and get back to you

**Comment by DeanmvSG** [comment]
Hi @Eireternal 
Sorry for the delay on replying to this! It looks like the `template` tag is missing on the section_button include.  For example instead of:

`{%- include 'section_button', item: '1', name: 'Section Buttons' -%}`
it should be
`{%- include 'section_button', template: '1', name: 'Section Buttons' -%}`

We are working on a fix/better version of the toolbox so that when you select an item it will show all the possible tags that the include/webapp/content section can have.

**Comment by DeanmvSG** [comment]
Hi @Eireternal 

A small update on this, we have actually removed the Section Button and Section Title areas from Siteglide Admin in v2.0.2.  Please see Luke's post here https://community.siteglide.com/t/private-beta-release-v2-0-2-08-08-2018/64/2 for more information on this change.

If you feel like this was a really useful section then let us know and we can discuss it more!
