### ISSUE TITLE
Error 500 when trying to render form

### ISSUE THREAD

**Issue by BSG83** [Siteglide/Siteglide-Admin-Feedback#30]
## Expected Behavior
Form should be rendered on page. Using

`{%- include_form 'custom_form_2', parent_resource_id: 'custom_form_2', layout: 'default', name: 'Contact2' -%}`

## Current Behavior
Error 500 is generated
![image](https://user-images.githubusercontent.com/32790757/47387352-0e551500-d707-11e8-9d7d-1cb0565d344b.png)

## Steps to Reproduce
1. Create Form
2. Using Insert From feature on page from the toolbox
3. Browse to page
4. Error 500 is shown

## Environment

* Windows 10
* Google Chrome 68.0.3440.75
* Siteglide Admin v2.0.0

**Comment by mattwalter91** [comment]
@BSG83 - Sorry, what site is this for?

**Comment by BSG83** [comment]
Hi,

Is there an update on this?
https://mva1.staging-oregon.near-me.com/mvahome is the page with the issue.

**Comment by MartinWysi** [comment]
Hi @BSG83 I've created a new form on your site and it looks like that one is working, so for now I'd suggest you just edit and use this one, which is called "Contact Form 3". 

Our developers will look into the previous form to see why it's not working and make sure it's not a wider problem. It is possible that it was created a while ago before we did the large form update. 

Thanks for reporting the issue, let us know if you need anything else in the meantime!
