### ISSUE TITLE
Menu Layout missing

### ISSUE THREAD

**Issue by BSG83** [Siteglide/Siteglide-Admin-Feedback#32]
## Expected Behavior
The default menu layout option should appear

## Current Behavior
Layout not found

## Steps to Reproduce
1. Create Menu
2. Add menu to page
3. Layout dropdown has no options
4.

## Environment
v 2.3.0

## Media
![image](https://user-images.githubusercontent.com/32790757/49137823-78a03d00-f2e5-11e8-938b-95c69d033736.png)

**Comment by mattwalter91** [comment]
@BSG83 - What instance is this?

**Comment by mattwalter91** [comment]
@BSG83 - I think it was mva1? I've pushed an update and the layouts now appear.

**Comment by mattwalter91** [comment]
@BSG83 - Sorry! I've fixed this now. You'll see the menu is now being rendered on the URL you sent over.
