### ISSUE TITLE
Section_title not showing up 

### ISSUE THREAD

**Issue by hmeichel** [Siteglide/Siteglide-Admin-Feedback#6]
## Expected Behavior

Section_Title should show up on page
## Current Behavior

Get an error on the page:
Liquid error: can't find LiquidView with path includes/section_title/. 

## Steps to Reproduce

1. Add Section_Title to page, using the sidebar Toolbox
2.
3.
4.

## Environment

Example: 
MacOS 10.9.5 - Firefox 61.0.1, Siteglide Admin v2.0.1
![screen shot 2018-08-06 at 1 15 41 pm](https://user-images.githubusercontent.com/38821382/43730896-dd26ceac-997a-11e8-893c-1af2554ec814.png)

## Media

![screen shot 2018-08-06 at 1 15 41 pm](https://user-images.githubusercontent.com/38821382/43730935-01d1fb82-997b-11e8-9b31-f9576289c743.png)

**Comment by DeanmvSG** [comment]
Hi @hmeichel 

Thanks for the report! I think this is the same issue as #3?  Can you try adding a `template` field to the tag?

**Comment by hmeichel** [comment]
Hi Dean - not sure if this is what you meant, but tried replaying item with template, but am still getting error
/Users/hmeichel/Desktop/Screen Shot 2018-08-06 at 1.30.35 PM.png

**Comment by hmeichel** [comment]
Hi Dean - not sure if this is what you meant, but tried replaying item with template, but am still getting error

**Comment by DeanmvSG** [comment]
Do you have any layouts in the code editor? 

Good news is this will be fixed with our new “insert modal” that will be released shortly!

**Comment by DeanmvSG** [comment]
Hi @hmeichel 

A small update on this, we have actually removed the Section Button and Section Title areas from Siteglide Admin in v2.0.2.  Please see Luke's post here https://community.siteglide.com/t/private-beta-release-v2-0-2-08-08-2018/64/2 for more information on this change.

If you feel like this was a really useful section then let us know and we can discuss it more!
